package com.example.smartstore.event;

public enum UserActionType {
    PRODUCT_LIST_VIEWED,
    PRODUCT_VIEWED,
    PRODUCT_SEARCHED,
    CART_CREATED,
    CART_OPENED,
    CART_VIEWED,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_REMOVED_FROM_CART,
    ASSISTANT_MESSAGE_SENT,
    ASSISTANT_SUGGESTION_REQUESTED,
    USER_LOGGED_IN
}
